project_id = "bhrnixwtnyetisnsjkhp"

[functions.market-data-sync]
verify_jwt = false

[functions.ai-signal-generator]
verify_jwt = false

[functions.news-scraper]
verify_jwt = false

[functions.trade-executor]
verify_jwt = false

[functions.risk-calculator]
verify_jwt = false

[functions.market-data-api]
verify_jwt = false

[functions.init-system]
verify_jwt = false
